### ISSUE TITLE
notmuch customisations don't work

### ISSUE THREAD

**Issue by TheKashe** [cmiles74/spacemacs-notmuch-layer#2]
Notmuch seems to ignore cusomisations settings. I've changed mode settings through customisation and have

` 
'(notmuch-archive-tags (quote ("+archive" "-inbox")))
`

in my .spacemacs, but pressing "a" still adds "archive_d_" tag rather than my custom tag. I also tried:

` 
(progn
    (require 'notmuch)
    (define-key notmuch-search-mode-map "a" nil)
    (define-key notmuch-search-mode-map "a"
    (lambda ()
      "mark message as archived"
      (interactive)
      (notmuch-search-tag (list "-inbox" "+archive"))
      (next-line) )))
`
but that doesn't redifine the behaviour of "a". If I use a key which is not used, e.g. "1", then it works.

I assume notmuch somehow overwrites my custom settings after .spacemacs initialisation is done, but I don't know enough to figure it out.

**Comment by TheKashe** [comment]
I had to add the below code to my .spacemacs in order to get SPC work. Of course notmuch-search-scroll-up needs to be bound to another key.

`
 (progn
    (require 'notmuch)
    ;;notmuch uses space key, which is very bad for space emacs
    (define-key notmuch-search-mode-map " " spacemacs-cmds))
`

**Comment by cmiles74** [comment]
I have most of my custom stuff in the `dotspacemacs/user-init` function, but there's not too much in mine. I tried adding the code below and it did work as expected. Could you give it a try and let me know if it solves your issue? Thank you!

    (defun notmuch/message-crazytalk ()
      (interactive)
      (notmuch-search-tag '("+wackadoodle" "-inbox" "-unread"))
      (notmuch-search-next-thread))

    (add-hook 'notmuch-search-mode-hook
              (lambda()
                (local-set-key (kbd "c") 'notmuch/message-crazytalk)
                (which-key-add-key-based-replacements
                  "c" "Tag message as crazy talk")))

**Comment by cmiles74** [comment]
This worked for me, so I'm closing this issue. `:-)`
